s <- svd(mat, 5, 7)
u<-as.matrix(s$u[, 1:5])
v<-as.matrix(s$v[, 1:7])
d<-as.matrix(diag(s$d)[1:5, 1:7])
newMat <- u%*%d%*%t(v)
colnames(newMat) = colnames(mat)
container = create_container(newMat, as.numeric(data.label[,1]), trainSize = 1:12,testSize = 13:18, virgin = FALSE)
models = train_models(container, algorithms = c("MAXENT", "SVM", "SLDA", "BAGGING","RF", "TREE"))
results = classify_models(container, models)
analytics = create_analytics(container, results)
summary(analytics)